name: Link Checker
on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * 1" # Runs every Monday
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Lychee Check
        uses: lycheeverse/lychee-action@v2
        id: lychee
        with:
          # Formatting fixed: 'args' now aligns correctly under 'with'
          args: >
            --verbose 
            --no-progress 
            --accept 200..499 
            --exclude "./docs/.*" 
            --exclude "https://github.com.*" 
            --exclude "https://community.api.video/.*" 
            --include-fragments '.' 
          fail: true 

      - name: Create Issue if links are broken
        if: failure() && steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Broken Links Found"
          content-filepath: ./lychee/out.md
          labels: documentation, automated-report
